name: gstark
description: A tax filing application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  intl: ^0.18.1
  http: ^1.2.1
  dropdown_button2: ^2.3.9
  supercharged: ^2.1.1
  simple_animations: ^5.0.2
  flutter_localization: ^0.2.0
#  connectivity_plus: ^6.0.1
  pdf: ^3.10.8
  open_file: ^3.3.2
  path_provider: ^2.1.2
  image_picker: ^1.0.7
  uuid: ^4.3.3
  flutter_pdfview: ^1.3.2
  flutter_cached_pdfview: ^0.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

