name: gstark
description: A tax filing application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.18
  http: ^0.13.5
  google_fonts: ^3.0.1
  flutter_svg: ^1.1.6
  get: ^4.6.5
  intl: ^0.17.0
  dropdown_button2: ^1.9.1
  supercharged: ^2.1.1
  simple_animations: ^4.0.1
  flutter_localization: ^0.1.10
  connectivity_plus: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

