name: gstark
description: A tax filing application.

publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  intl: ^0.18.1
  http: ^1.2.1
  dropdown_button2: ^2.3.9
  supercharged: ^2.1.1
  simple_animations: ^5.0.2
  flutter_localization: ^0.2.0
#  connectivity_plus: ^6.0.1
  pdf: ^3.10.8
  open_file: ^3.3.2
  path_provider: ^2.1.2
  image_picker: ^1.0.7
  uuid: ^4.3.3
  flutter_pdfview: ^1.3.2
  flutter_cached_pdfview: ^0.4.2
  flutter_excel: ^1.0.0
  easy_pdf_viewer: ^1.0.8
  excel: ^2.0.0-nullsafety.3
  horizontal_data_table: ^4.1.4
  pdf_render: ^1.4.0
  flutter_image_compress: ^1.1.1
  #phone call
  url_launcher: ^6.3.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/

